version: "3"

services:
  mc:
    image: itzg/minecraft-server
    container_name: minecraft-charlotte-stg
    ports:
      - 48610:48600
    environment:
      EULA: "TRUE"
      MEMORY: "8G"
      VERSION: "1.20"
      TYPE: "VANILLA"
      STOP_SERVER_ANNOUNCE_DELAY: 10
      RCON_PASSWORD: "charlotte486486"
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - /home/karia/minecraft/staging/data:/data

