version: "3"

services:
  mc:
    image: itzg/minecraft-server
    container_name: minecraft-charlotte-prd
    ports:
      - 48600:48600
    environment:
      EULA: "TRUE"
      MEMORY: "8G"
      VERSION: "1.20.1"
      TYPE: "SPIGOT"
      MODS: "https://mediafilez.forgecdn.net/files/4586/220/worldedit-bukkit-7.2.15.jar"
      SPIGET_RESOURCES: 18494
      STOP_SERVER_ANNOUNCE_DELAY: 10
      RCON_PASSWORD: "charlotte486486"
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - /home/karia/minecraft/production/data:/data
  backup:
    image: itzg/mc-backup
    container_name: backup-charlotte-prd
    environment:
      PRUNE_BACKUPS_DAYS: 30
      BACKUP_INTERVAL: "30m"
      PAUSE_IF_NO_PLAYERS: "false"
      RCON_HOST: mc
      RCON_PASSWORD: "charlotte486486"
    volumes:
      - /home/karia/minecraft/production/data:/data:ro
      - /home/karia/minecraft/production/backups:/backups
    network_mode: "service:mc"

